@startuml

class Salle {
    - id : int
    - nom : string
    - batiment : string
    - capacite : int
    - type : string
    - active : bool
    - created_at : DateTime
    - updated_at : DateTime
}

class Reservation {
    - id : int
    - salle_id : int
    - responsable : string
    - email : string
    - motif : string
    - date_debut : DateTime
    - date_fin : DateTime
    - statut : string
    - created_at : DateTime
    - updated_at : DateTime
}

Salle "1" -- "0..*" Reservation

@enduml
